### ISSUE TITLE
[Enhancement] Use poetry for dependency management

### ISSUE THREAD

**Issue by ronnyfriedland** [telekom-mms/falcon-eye-monitoring#27]
### Description

Avoid installing F.E.M. related dependencies without virtual env.

**Comment by 2Fraennk** [comment]
I think we don't need a virtual environment for poetry, since there is a dedicated container for testing.
So I suggest to deactivate virtual environment by adding the following line to the Dockerfile before installing poetry:

"...
RUN poetry config virtualenvs.create false
RUN poetry install
..."

What do you think?
